version: '3'
services:
  vsftpd:
    image: fauria/vsftpd
    container_name: vsftpd
    restart: no
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./docker-ftp-data:/home/vsftpd
    environment:
      - FTP_USER=dousx
      - FTP_PASS=fpN2lM2bV
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - LOCAL_UMASK=022